name: SDK chain tests
on:
  push:
    paths-ignore:
      - "**.md"

permissions:
  contents: read

env:
  # Allow ddev get to use a GitHub token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-standalone-bouncer:
    name: Run Standalone Bouncer tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/cs-standalone-php-bouncer/.github/workflows/php-sdk-development-tests.yml@22b9a34f4623d3380e970b4c7569fe4d9397f1eb
    with:
      php_common_json: '["${{ github.ref_name }}"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
      remediation_engine_json: '["main"]'
      bouncer_lib_json: '["main"]'

  test-bouncer-lib:
    name: Run Bouncer lib tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-cs-bouncer/.github/workflows/php-sdk-development-tests.yml@c15ac30dfb66f51c0794cb02f4449056116c85bf
    with:
      php_common_json: '["${{ github.ref_name }}"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
      remediation_engine_json: '["main"]'

  test-remediation-engine:
    name: Run Remediation Engine tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-remediation-engine/.github/workflows/php-sdk-development-tests.yml@1ba21c9b35fa85c4bcb8b4c1c31c36f2d6237f73
    with:
      php_common_json: '["${{ github.ref_name }}"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
    secrets:
      TEST_MACHINE_ID: ${{ secrets.TEST_MACHINE_ID }}
      TEST_MACHINE_PWD: ${{ secrets.TEST_MACHINE_PWD }}

  test-lapi-client:
    name: Run Lapi client tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-lapi-client/.github/workflows/php-sdk-development-tests.yml@0e1a14b1b5225fb5b6c3e880a0fe20fc3d00ba23
    with:
      php_common_json: '["${{ github.ref_name }}"]'

  test-capi-client:
    name: Run Capi client tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-capi-client/.github/workflows/php-sdk-development-tests.yml@7d29f10236fe0a0ba6f9d1c628e4e01e61012fd0
    with:
      php_common_json: '["${{ github.ref_name }}"]'
    secrets:
      TEST_MACHINE_ID: ${{ secrets.TEST_MACHINE_ID }}
      TEST_MACHINE_PWD: ${{ secrets.TEST_MACHINE_PWD }}
      ENROLLMENT_KEY: ${{ secrets.TEST_ENROLLMENT_KEY }}

  test-magento-engine:
    name: Run Magento 2 Engine module tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/magento-cs-extension/.github/workflows/php-sdk-development-tests.yml@cf9e25d0753d46d993d61a9fb8113d7e4f91c31f
    with:
      php_common_json: '["${{ github.ref_name }}"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
      remediation_engine_json: '["main"]'
      bouncer_lib_json: '["main"]'
    secrets:
      MACHINE_ID: ${{ secrets.TEST_MACHINE_ID }}
      MACHINE_PASSWORD: ${{ secrets.TEST_MACHINE_PWD }}
      ENROLL_KEY: ${{ secrets.TEST_ENROLLMENT_KEY }}
      M2_COMPOSER_AUTH: ${{ secrets.M2_AUTH }}
