name: SDK chain tests
on:
  push:
    paths-ignore:
      - "**.md"

permissions:
  contents: read

env:
  # Allow ddev get to use a GitHub token to prevent rate limiting by tests
  DDEV_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test-standalone-bouncer:
    name: Run Standalone Bouncer tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/cs-standalone-php-bouncer/.github/workflows/php-sdk-development-tests.yml@21a85d5696ba607e2028330c4ddda4b5e361547a
    with:
      php_common_json: '["${{ github.ref_name }}"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
      remediation_engine_json: '["main"]'
      bouncer_lib_json: '["main"]'

  test-bouncer-lib:
    name: Run Bouncer lib tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-cs-bouncer/.github/workflows/php-sdk-development-tests.yml@c2aaf185542d56c4731822e833aa4613b0143a5e
    with:
      php_common_json: '["${{ github.ref_name }}"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
      remediation_engine_json: '["main"]'

  test-remediation-engine:
    name: Run Remediation Engine tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-remediation-engine/.github/workflows/php-sdk-development-tests.yml@0f0f1b16ab4f6ca3ad0525e03a6d88675a9baa99
    with:
      php_common_json: '["${{ github.ref_name }}"]'
      lapi_client_json: '["main"]'
      capi_client_json: '["main"]'
    secrets:
      TEST_MACHINE_ID: ${{ secrets.TEST_MACHINE_ID }}
      TEST_MACHINE_PWD: ${{ secrets.TEST_MACHINE_PWD }}

  test-lapi-client:
    name: Run Lapi client tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-lapi-client/.github/workflows/php-sdk-development-tests.yml@abf5fac68b433c52cb31477f8c03130c939f8b72
    with:
      php_common_json: '["${{ github.ref_name }}"]'

  test-capi-client:
    name: Run Capi client tests
    if: ${{ !contains(github.event.head_commit.message, 'chore(') }}
    uses: crowdsecurity/php-capi-client/.github/workflows/php-sdk-development-tests.yml@e484c553a3b92d6f1b69df0cd407286de80af8a8
    with:
      php_common_json: '["${{ github.ref_name }}"]'
    secrets:
      TEST_MACHINE_ID: ${{ secrets.TEST_MACHINE_ID }}
      TEST_MACHINE_PWD: ${{ secrets.TEST_MACHINE_PWD }}
      ENROLLMENT_KEY: ${{ secrets.TEST_ENROLLMENT_KEY }}
